### ISSUE TITLE
cert-manager-plugin: translate some Secret annotation on sync from host

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster-plugins#22]
When syncing a Secret from the host cluster to vcluster we should fix the value of the "[cert-manager.io/certificate-name](http://cert-manager.io/certificate-name)" and "[cert-manager.io/issuer-name](http://cert-manager.io/issuer-name)" annotations to contain the correct name of the Certificate.

Related to: [https://loft-sh.slack.com/archives/C01N273CF4P/p1670587259210579?thread_ts=1670501735.883589&cid=C01N273CF4P](https://loft-sh.slack.com/archives/C01N273CF4P/p1670587259210579?thread_ts=1670501735.883589&cid=C01N273CF4P)

**Comment by philimonoff** [comment]
Also `cert-manager.io/issuer-name` should be fixed too.
