### ISSUE TITLE
cert-manager-plugin should operate at namespace scope only

### ISSUE THREAD

**Issue by stan-yago** [loft-sh/vcluster-plugins#40]
cert-manager-plugin error messages are variants of the following:

reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262 Failed to list/watch *v1.Secret, *v1.Certificate,*v1.Issuer is forbidden: User "system:serviceaccount:ns-vcluster:vc-ns-vcluster" cannot list resource "secrets" in API group "" at the cluster scope: Azure does not have opinion for this user.

**Comment by facchettos** [comment]
Hi @stan-yago , thanks for the issue. We are currently moving to a new version of plugins, so if we implement it it will most likely be done there.
