### ISSUE TITLE
[cert-manager] get clusterIssuer reference in vcluster

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [loft-sh/vcluster-plugins#44]
As mentionned [in code](https://github.com/loft-sh/vcluster-plugins/blob/418647ae31e3f108adb4b95a86bc87bf211074fb/cert-manager-plugin/pkg/syncers/certificates/translate.go#L53), host cluster clusterIssuers are not mapped by the cert-manager plugin.

Would it be possible to implement it?

**Comment by facchettos** [comment]
It would technically be possible I believe, however that would require to have extended rbac for the plugin, I will ask around for context and circle back to you. Also, we are moving to v2 of plugins, so if we are implementing it in the future that will be done there.

**Comment by facchettos** [comment]
actually, we don't have plans to implement this as of now, since that would require us to be able to list secrets in many namespaces, which I don't think is a good idea
